### ISSUE TITLE
Subtracting an integer from a variable without space fails

### ISSUE THREAD

**Issue by mweisgut** [hyrise/sql-parser#120] opened 2019-04-26 12:58 UTC
The first example is evaluated as invalid whereas the second example is evaluated as valid.

Example 1:
```sql
SELECT x, y
FROM table1
WHERE x=y-42
```

Example 2:
```sql
SELECT x, y
FROM table1
WHERE x=y- 42
```

**Comment by mrzzzrm** [comment] 2019-04-26 14:04
Duplicate of #93

**Closed by mrzzzrm** 2019-04-26 14:04 UTC
